name: Build and Push Docker Image

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      commit_hash: ${{ steps.get_commit_hash.outputs.commit_hash }}

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Checkout upstream repository
        run: git clone https://github.com/coredhcp/coredhcp.git

      - name: Get commit hash
        id: get_commit_hash
        run: |
          cd coredhcp
          UPSTREAM_COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "commit_hash=$UPSTREAM_COMMIT_HASH" >> $GITHUB_ENV
          echo "::set-output name=commit_hash::$UPSTREAM_COMMIT_HASH"
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: brennoo/coredhcp:latest, brennoo/coredhcp:${{ steps.get_commit_hash.outputs.commit_hash }}
          outputs: type=oci,dest=/tmp/coredhcp_image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: coredhcp_image
          path: /tmp/coredhcp_image.tar

  push:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: coredhcp_image
          path: /tmp

      - name: Load, tag, and push Docker image
        run: |
          docker load --input /tmp/coredhcp_image.tar
          IMAGE_TAG=brennoo/coredhcp:${{ needs.build.outputs.commit_hash }}
          docker tag $IMAGE_TAG brennoo/coredhcp:latest
          echo "Pushing Docker image with tag $IMAGE_TAG"
          docker push $IMAGE_TAG
          docker push brennoo/coredhcp:latest
